### PR TITLE
mark non-bio-related packages

### PR DESCRIPTION
**Pull request by daler**
I read through the summaries of all 2613 current packages, and indicated which are not technically bio-related. We can now subset the figures by these criteria or use them to guide a round of cleanup in the repo.

It would be helpful if someone could at least spot-check my work to find false positives. False negatives will take more time (Note that I did mark things like snakemake and involucro as non-bio related)

cc @johanneskoester @epruesse

### CODE REVIEW

**Comment by epruesse** [comment]
>I read through the summaries of all 2613 current packages,

@daler Wow!

**Comment by daler** [comment]
@cbrueffer thanks, was going cross-eyed by the end!

**Comment by cbrueffer** [comment]
@daler no wonder, great work!

**Comment by johanneskoester** [comment]
Great, thanks @daler!! Yeah, snakemake is not strictly bio related, but I would like to keep it in bioconda, at least for now.

**Comment by johanneskoester** [comment]
I went through the first 200 or so, and could not find anything to fix (no time to do all of them, sorry). Shall we merge this?

**Comment by cbrueffer** [comment]
:+1: from me

**Pull request merged**
